version: '3'
services:

  db:
    restart: always
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/mastodon/postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/mastodon/redis:/data
